---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redmine
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: my-redmine
  template:
    metadata:
      labels:
        app: my-redmine
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        env:
        - name: REDMINE_DB_POSTGRES
          value: database
        - name: REDMINE_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: redmine_key_base 
        - name: REDMINE_DB_DATABASE 
          value: testdatabase
        - name: REDMINE_DB_USERNAME
          value: testuser
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: pass       
        ports:
        - containerPort: 3000
          protocol: TCP
